### ISSUE TITLE
proposal: user display names

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#116]
This can be a unique username or a non-unique display name for each user. It's worth ignoring what Hacker News or Product Hunt does here and instead asking which is better.

We should use a new table if it's to be a unique username. If it's to be a non-unique display name, it might be better to come from the `user_metadata` object.

I'd like to hear some thoughts.

CC @lambtron and @thorwebdev

**Comment by thorwebdev** [comment]
Yah, storing a display name in `user_metadata` works. Just make sure you restrict the length to not blow up the cookie too much.

For unique usernames, I'd recommend creating a users table on the public schema. You can add a trigger to the `auth.users` table to automatically sync the Auth users to the public.users table. See an example here: https://github.com/vercel/nextjs-subscription-payments/blob/main/schema.sql#L19-L32

**Comment by iuioiua** [comment]
We'll go ahead with a non-unique display name for each user.
