### ISSUE TITLE
Missing deno.land/logo.svg due to net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 200

### ISSUE THREAD

**Issue by huai-jie** [denoland/saaskit#118]
Missing deno logo on deno.com/saaskit index page

**To Reproduce** Steps to reproduce the behavior:

1. Go to '[deno.com/saaskit](https://deno.com/saaskit)'
2. Scroll down to 'Built with modern technologies' section

**Expected behavior** Deno logo should be shown

**Screenshots** 
![image](https://user-images.githubusercontent.com/58794979/233987992-5901aa50-138c-4f8d-8605-359c9acbb867.png)

**Additional context** 
Change the img src from `https://deno.land/logo.svg` to `https://deno.com/logo.svg` should fix the problem

**Comment by huai-jie** [comment]
Resolved!

**Comment by iuioiua** [comment]
Sorry I didn't get back to you, @huai-jie. We actually fixed this a few hours before you raised this issue. It was just a matter of some server-side cache (I assume) clearing. Either way, good spot and thanks for bringing it up!
