### ISSUE TITLE
proposal: make Stripe optional

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#124]
See:
* https://discord.com/channels/684898665143206084/1085986084653109438/1096714267601948762
* https://discord.com/channels/684898665143206084/1085986084653109438/1086224107022069841

**Comment by iuioiua** [comment]
I've played around with the implementation of this idea. It adds a layer of complexity to the codebase as a whole, especially around aspects that would be paywalled (i.e. premium features). I don't think this is worth pursuing for now, given that only a few people have expressed interest.

This can be revisited if there's enough demand for the modification.

**Comment by huai-jie** [comment]
Oh, I am really wondering how to implement the premium features without online payment processing services like Stripe.

It is possible to make it like this? Separate the `without Stripe` version from the general branches that are `with Stripe`.

> Database management with [Deno KV](https://deno.com/manual/runtime/kv), which provides zero config durable data storage. Prefer using Supabase for data storage? [Check out this version of SaaSKit](https://github.com/denoland/saaskit/tree/3b1b14a97eef8859596015b22557d575d3b63c09).

**Comment by evilmonkey19** [comment]
I like the idea, but I feel it is much more natural to embed it as some add-on.
