### ISSUE TITLE
Comment href link to undefined in local 

### ISSUE THREAD

**Issue by huai-jie** [denoland/saaskit#143]
**Describe the bug** 
Comment href link to undefined route due to missing `id` property.

**To Reproduce**
1. Go to the index page.
2. Click on the `Comments` button

**Expected behavior**
Should go to the item page

**Screenshots**
![image](https://user-images.githubusercontent.com/58794979/235603544-013457eb-5fd3-4bfa-857a-9f4dbd812ff1.png)

**Additional context** 
- Add an `id` property for `item` at `getAllItems()` should fix it.
- https://saaskit.deno.dev/ is down ATM so the screenshot provided is in locally.

**Comment by iuioiua** [comment]
Hm... This is working fine for me on my local machine. You could try resetting the database by running `deno run -A tools/reset_kv.ts`. Does that work?

**Comment by huai-jie** [comment]
It works. Seem like it is due to KV data properties having some changes. 

Run: `deno run --unstable -A tools/reset_kv.ts`.

**Comment by iuioiua** [comment]
Nice! Ah, yes, I forgot the `--unstable` :sweat_smile:
