### ISSUE TITLE
bug: password reset flows on local dev environment

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#157]
Neither @thorwebdev nor I can reproduce the password reset flow locally. I assume this is because such a flow doesn't support sending external emails, though I could be wrong. We'll need to confirm this fact.

**Comment by thorwebdev** [comment]
@iuioiua sorry, for me it wasn't working on my hosted project. Locally you can use the inbucket to test auth emails:
```bash
supabase status

 Inbucket URL: http://localhost:54324
```

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/5748289/236125274-36486661-fa1a-4998-b84d-722209076c81.png">

**Comment by huai-jie** [comment]
I have tested password reset flows on the local dev environment with inbucket. It works fine for me.

**Comment by iuioiua** [comment]
This is no longer an issue since #192.
