### ISSUE TITLE
Bug: upvoting from within the /item does not reflect the vote count on the root page

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#189]
**Describe the bug**
Upvoting from within the /item does not reflect the vote count on the root page.

**To Reproduce**
1. On the root page click on an item
2. From within the /item, click on the upvote button. check that it correctly update the vote count.
3. Go back to the root page. The vote count for the item you've just upvoted is not updated.
4. if you go to the /item page again, the count is the correct one.

**Expected behavior**
The vote count should always be consistent across pages for the same item.

**Comment by iuioiua** [comment]
Hi @brunocorrea23, are you refreshing the homepage after upvoting the item on the item page? If not, this is expected behaviour and not a bug but a missing feature.

For me, after refreshing the homepage, the score is being updated correctly.

**Comment by iuioiua** [comment]
This appears to just be a feature that the site doesn't have. After @huai-jie started work on the implementation, it's become apparent to us both that it's not worth the added cost of complexity. So we will not implement it. Either way, thanks for the suggestion, @brunocorrea23! 👍🏾
