### ISSUE TITLE
Supabase why ? 

### ISSUE THREAD

**Issue by mrtornado** [denoland/saaskit#191]
Why is this using supabase when we have deno.kv ?  isn't the hole point in using the deno.kv so the database is replicated ?

**Comment by iuioiua** [comment]
The current auth solution uses Supabase but we're working on our own auth solution based on Deno KV 💪🏾

**Comment by mrtornado** [comment]
that's what I'm waiting for ... 👯 because for sure I will move all my projects to Fresh & Deno as soon we pass the beta state on Deno.Kv

**Comment by iuioiua** [comment]
I'll close this now because the design decision to move to Deno KV has already been made. You can see progress by following #192 and keeping an eye on releases in the coming weeks.
