### ISSUE TITLE
deno task start does not run anymore

### ISSUE THREAD

**Issue by Sorikairox** [denoland/saaskit#194]
**Describe the bug** A clear and concise description of what the bug is.

I try to run deno task start right after cloning, here is what happens:
 ```
 deno task start
Task start deno run --unstable -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 24 routes and 2 islands.
error: Uncaught TypeError: parser error: expected token Close, found '{' of type Open
        pattern: new URLPattern({ pathname: path }),
                 ^
    at new URLPattern (ext:deno_url/01_urlpattern.js:70:28)
    at buildInternalRoutes (https://deno.land/x/rutt@0.1.0/mod.ts:223:18)
    at Module.router (https://deno.land/x/rutt@0.1.0/mod.ts:275:7)
    at ServerContext.handler (https://deno.land/x/fresh@1.1.5/src/server/context.ts:313:24)
    at start (https://deno.land/x/fresh@1.1.5/src/server/mod.ts:70:21)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async file:///Users/sorikairo/Code/savory/tst/saaskit/main.ts:14:1
```
**To Reproduce** Steps to reproduce the behavior:

1. Git clone the repository
2. Setup your .env as expected by the readme
3. Try to run deno task start
4. Cry

**Expected behavior** A clear and concise description of what you expected to
happen.
Should work as it was working 30 minutes ago...

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screenshot 2023-05-14 at 18 21 53](https://github.com/denoland/saaskit/assets/38007824/b99149c8-2b6c-4478-99ca-da6735c15235)

**Desktop (please complete the following information):**

- OS: Apple M2 Pro Ventura 13.2

deno 1.33.0 (release, aarch64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3

**Additional context** Add any other context about the problem here.

Tried to run `deno cache --reload main.ts` just in case, no changes.
It broke out of a sudden, for no apparent reason.

**Comment by Sorikairox** [comment]
Update: Seems to be related to my .env file. Working on it to find out why. Seems to be char encoding issue

**Comment by iuioiua** [comment]
What happens when you delete your `DENO_DEPLOYMENT_ID` environmental variable?

**Comment by iuioiua** [comment]
Note: this is the same issue as #167.

**Comment by Sorikairox** [comment]
That was it. Sorry for the duplication.

**Comment by ajile-in** [comment]
> 

It works when you delete the `DENO_DEPLOYMENT_ID` from `.env`, as now it is not needed.
