### ISSUE TITLE
bug: vote count not working properly

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#208]
**Describe the bug**
sometimes clicking on the upvote button doesn't update the status
sometimes clicking on the upvote button simply changes the color of the button, but not the number for the vote count.
sometimes the vote count is gray on the main page, but red in the /item page.
sometimes refreshing the page changes the vote state.

**To Reproduce** Steps to reproduce the behavior:
Click many times on the upvote button on the main page and on the /item page
It is difficult to give specific directions on how to reproduce the issue because the behavior is not consistent. Doing the same thing yields different results from time to time.
Hopefully you can easily see the same issue as I'm seeing now. Please let me know if you are not experiencing this same bug and I can try to isolate it better.

**Comment by huai-jie** [comment]
Do you still experience this ? It should be resolved in this https://github.com/denoland/saaskit/pull/217
