### ISSUE TITLE
proposal: show number of comments of an item on the main page next to the timestamp

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#209]
Similar to what Hacker News does (https://news.ycombinator.com/)
![Screenshot 2023-05-18 at 15 56 20](https://github.com/denoland/saaskit/assets/8139585/5f1f571f-6052-42d0-8148-f6de8977c866)

**Comment by iuioiua** [comment]
We previously had comment counts but removed them in #171 because it wasn't worth the added complexity and overhead. However, if [`Deno.Kv.count()`](https://github.com/denoland/deno/issues/18965) is implemented, it'll be worth considering adding this feature back in.

**Comment by lino-levan** [comment]
@iuioiua would you be willing to bring this back via an index? Something like a cached comment count on the post object itself?

**Comment by iuioiua** [comment]
Slightly likely not. However, I'd be happy to consider a PR that does this without incurring too much of a complexity cost.

**Comment by iuioiua** [comment]
It seems this feature would incur a similar complexity cost that [voting functionality has incurred on item logic](https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/utils/db.ts#L306-L412), which has been a bit of a pain point for the codebase, IMO. For that reason, I'd rather not have this feature. WDYT, @brunocorrea23?

**Comment by iuioiua** [comment]
Gently pinging @brunocorrea23.
