### ISSUE TITLE
proposal: ability to reply to a specific comment on the /item page

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#210]
Similar to what Hacker News does: https://news.ycombinator.com/item?id=35990552

**Comment by iuioiua** [comment]
Yeah, I like this idea. Our approach was to get basic comments working and tackle this feature at some point after that. A PR would be welcome!

**Comment by iuioiua** [comment]
For the same reason I closed #234, I'll close this issue for now. Again, while this is a lovely idea, Deno Hunt's feature set is satisfactory. We can still revisit this in the future if we think Deno Hunt can do with some more features. Thanks, @brunocorrea23!
