### ISSUE TITLE
proposal: complete homepage functionality

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#211]
This includes:
- [x] Pagination using a `?page=` URL query with items per page length of 10.

**Comment by brunocorrea23** [comment]
@iuioiua , what do you believe is left to be done here in this issue?

**Comment by iuioiua** [comment]
Item numbering, which should be easy.

**Comment by iuioiua** [comment]
One more. Right now, we can only see items up till 1 week ago. It'd be nice to have a simple selector to change this. I think 1 week ago, 1 month ago and all-time ago are decent options. It could be controlled via a simple `?time-ago=` URL query.

**Comment by iuioiua** [comment]
This was completed in #257.
