### ISSUE TITLE
proposal: trim Docker documentation

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#227]
I have no experience with Docker documentation, but I have some ideas of how it could be cleaned up:

- [x] Remove: https://github.com/denoland/saaskit/blob/f2364de163054ac99bb2bbf150c92159d9e73779/README.md?plain=1#L33
- [x] Create this file in the directory so the user doesn't have to: https://github.com/denoland/saaskit/blob/f2364de163054ac99bb2bbf150c92159d9e73779/README.md?plain=1#L188-L200
- [x] Ditto: https://github.com/denoland/saaskit/blob/f2364de163054ac99bb2bbf150c92159d9e73779/README.md?plain=1#L202-L210
- [x] Ditto: https://github.com/denoland/saaskit/blob/f2364de163054ac99bb2bbf150c92159d9e73779/README.md?plain=1#L212-L232
- [x] Add a step number to each instruction, like other sections in the README.

Please correct me if I'm wrong on any of these.

**Comment by lambtron** [comment]
this makes sense to me. i can create a PR for it.

**Comment by iuioiua** [comment]
Some of this was done in #238.

**Comment by lambtron** [comment]
This PR addresses the remaining tasks in this issue: https://github.com/denoland/saaskit/pull/253

**Comment by iuioiua** [comment]
This has been completed in #253.
