### ISSUE TITLE
todo: de-deuplicate code between user page and home page

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#232]
There's code that's been duplicated on both the user page and the home page. Such code should be cleaned up and centralised. Tests would also be welcomed.

**Comment by baqirkhan** [comment]
Could you point it out to me the file names where this duplicate code is present ? I would like to take a stab at this.

**Comment by iuioiua** [comment]
Home page: `/routes/index.tsx`
User page: `/routes/user/[username].tsx`

**Comment by iuioiua** [comment]
To clarify, what I had in mind was to move the duplicated code to `/utils` or into `/components`, depending on which code it is.

**Comment by iuioiua** [comment]
Fixed in #237.
