### ISSUE TITLE
proposal: allow for a custom ranking algorithm, not just votes

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#234]
Today DenoHunt uses only upvotes to rank the items. It would be good to be able to support a ranking algorithm that involves the 'age' and 'engagement' of the item/post.

It would be nice to discuss how to do the pagination in this case.

**Comment by iuioiua** [comment]
This can be done via a `?order=` URL parameter which controls the `items.sort()` predicate. Let's focus on this after v1 😄

**Comment by roberto-morado** [comment]
## Assign me! 👋

**Comment by iuioiua** [comment]
> ## Assign me! 👋

Done! Previously, I wanted to do this after v1. But since you've offered, I'm happy to have this now 😄

**Comment by iuioiua** [comment]
Change of plans - While this is a fantastic idea, Deno Hunt is now at a point where we're happy with its feature set, even though it doesn't have complete feature parity with Hacker News. I'll close this issue now, as we're not planning on adding this to Deno Hunt soon. This is the case now, but it could change if we decide to extend Deno Hunt's capabilities. Either way, thanks @brunocorrea23 and @roberto-morado!
