### ISSUE TITLE
bug: item doesn't support more than 10 comments and throws a server 500 error

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#256]
Simply try to add more than 10 comments on any item.

For example, check: https://saaskit.deno.dev/item/7c47b301-17b5-4864-b7c5-e970d428877f

500 internal error: too many ranges (max 10)

<img width="431" alt="Screenshot 2023-06-08 at 10 52 00" src="https://github.com/denoland/saaskit/assets/8139585/ff1cd3cc-c56c-4f50-a918-18d0bf4ef746">

**Comment by iuioiua** [comment]
This has been fixed in #257.
