### ISSUE TITLE
todo: bump fresh to 1.2.0

### ISSUE THREAD

**Issue by huai-jie** [denoland/saaskit#260]
I saw fresh 1.2.0 has been released! Let's try the new features of it! 🤩

**Comment by iuioiua** [comment]
Agreed! It'll be cool to see all the new features of Fresh being taken advantage of! References for those wanting to implement this:
* https://deno.com/blog/fresh-1.2
* https://github.com/denoland/fresh/compare/1.1.6...1.2.0

**Comment by iuioiua** [comment]
This was completed in #274.
