### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'unit_amount')

### ISSUE THREAD

**Issue by nicu-chiciuc** [denoland/saaskit#261]
**Describe the bug**
When clicking the `Pricing` button on the homepage I get the `TypeError: Cannot read properties of null (reading 'unit_amount')` in `pricing.tsx`.

**To Reproduce**
0. Clone and setup based on Readme.
1. Go to http://localhost:8000/pricing
2. See error on screen, also see error in terminal:
```
An error occurred during route handling or page rendering. TypeError: Cannot read properties of null (reading 'unit_amount')
    at comparePrices (file:///Users/nicu/dev/my/legis_gpt/saaskit/routes/pricing.tsx:18:52)
    at Array.sort (<anonymous>)
    at GET (file:///Users/nicu/dev/my/legis_gpt/saaskit/routes/pricing.tsx:28:27)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async handler (file:///Users/nicu/dev/my/legis_gpt/saaskit/routes/_middleware.ts:29:15)
    at async Server.handler (https://deno.land/x/fresh@1.1.6/src/server/context.ts:334:19)
    at async Server.#respond (https://deno.land/std@0.178.0/http/server.ts:299:18)
```

**Expected behavior**
I don't expect an error.

**Screenshots**
<img width="1792" alt="Screenshot 2023-06-17 at 15 01 35" src="https://github.com/denoland/saaskit/assets/4076804/c17c886d-739a-4c34-b50f-17e4089a9afc">

**Desktop**
- OS: Apple M1 Pro
- Browser Chrome
- Version 114.0.5735.133 (Official Build) (arm64)

**Additional context** 
I didn't look too much into it, but I didn't expect to get an `any` from the `strip.products.list`, which I assume causes the error.

![Screenshot 2023-06-17 at 15 04 16](https://github.com/denoland/saaskit/assets/4076804/dfed71bc-0799-4fb6-a35f-c4bcc703641b)

**Comment by iuioiua** [comment]
Hi @nicu-chiciuc, I see that you followed the setup in the README. Specifically, did you complete the actions listed in the [Payments and Subscriptions (Stripe)](https://github.com/denoland/saaskit/blob/main/README.md#payments-and-subscriptions-stripe) section?

**Comment by iuioiua** [comment]
To elaborate, the error you're getting appears to be caused by `productA.default_price` being `null` [here](https://github.com/denoland/saaskit/blob/5e19532590420ccfa2b3ff58e9e9ec233dbeecdc/routes/pricing.tsx#L18). This would be caused by the Stripe products not being setup correctly or similar, rather than a type error.

**Comment by nicu-chiciuc** [comment]
I understand. That runtime error could've been prevented if this assertions aren't used. My PR makes this more explicit.

**Comment by iuioiua** [comment]
Could you please clarify whether you completed the actions listed in the [Payments and Subscriptions (Stripe)](https://github.com/denoland/saaskit/blob/main/README.md#payments-and-subscriptions-stripe) section of the README?

**Comment by nicu-chiciuc** [comment]
I did initially. Then, in order to confirm that I didn't change anything else, I've cloned the repo once again and just copied over my `.env` file.
