### ISSUE TITLE
todo: improve test coverage

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#267]
The aim is to have [code coverage](https://app.codecov.io/gh/denoland/saaskit) at 100%.

**Comment by mbhrznr** [comment]
would love to tackle this!

**Comment by iuioiua** [comment]
For those wanting to help, I'd welcome a PR that takes care of test coverage for `Vote` within `utils/db.ts`.

**Comment by mbhrznr** [comment]
since i already familiarized myself w/ `utils` i'd tackle that one as well.

**Comment by iuioiua** [comment]
We're now at almost 100%! Thank you to all that helped out this.

**Comment by iuioiua** [comment]
Re-opening this as coverage has slipped a little as things have changed.

**Comment by iuioiua** [comment]
I've expanded the coverage surface area in #495.

**Comment by iuioiua** [comment]
While not at 100%, test coverage is more than sufficient.
