### ISSUE TITLE
bug: fix /stats charts axis scale

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#276]
There are currently two issues with the scales for the axis in the /stats charts:

- [ ] y-axis scale should consist of natural numbers only and start from zero.
- [ ] x-axis dates should be sequential. Today it is only showing the dates for which it has data for. All dates within the interval should be shown. If there is no event for that date, simply assign a 'zero' to it.

<img width="628" alt="Screenshot 2023-06-21 at 00 03 32" src="https://github.com/denoland/saaskit/assets/8139585/046cf3e6-9fb5-47ff-8779-a5c6e702bbb3">

**Comment by mbhrznr** [comment]
i'd give this one a spin.

**Comment by iuioiua** [comment]
@mbhrznr, please note #287 fixed the y-axis so it starts at 0 now.
