### ISSUE TITLE
bug: onChange for PageSelector not working as expected after Fresh 1.2 update

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#291]
**Describe the bug**
Before #274 , the PageSelector was working as expected.
On the update to Fresh 1.2, the code on PageSelector.tsx `onchange="this.form.submit()"` wasn't being recognized anymore and it had to be changed to `onChange={() => this.form.submit()}`, but it seems it doesn't have the same behavior.

**To Reproduce**
1. click on the time selector All Time to guarantee you have more than 10 items to be shown
2. click on the arrows on the page selector to try to switch pages
3. notice that the page doesn't change. It only changes if you press enter.

**Comment by huai-jie** [comment]
Hmm.. I think it is the correct behavior in this case as `PageSelector` component is being rendered by `Fresh` with zero js. 
(I don't know why it worked previously, though.)

The `onChange` event alone cannot be used to submit a form without any scripting. The onChange event is typically used to detect changes in the value of an input field or select element, but it does not have a built-in mechanism to trigger form submission.

It could be resolved by adding a submit button in the form

Or 

Moving it to the islands and then adding `page-selector` as the form's id
```
<form id="page-selector"> 
     <input 
        onChange={() => (document.getElementById('page-selector') as HTMLFormElement)?.submit()}
     />
</form>
```

Correct me if I am wrong or missing something else.
