### ISSUE TITLE
bug: blog posts dark theme styling is incorrect 

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#301]
As pointed out in #299, the dark theme styling for rendered markdown files is incorrect. A suggestion would be to add custom CSS for markdown files. However, other solutions are welcome.

<img width="1470" alt="image" src="https://github.com/denoland/saaskit/assets/29347852/40c5e410-f3f8-416d-903b-ca1d3b8f14e7">

**Comment by niklasmtj** [comment]
The moment you want to tackle the issue and see that it is already done. Good job 😅
