### ISSUE TITLE
feature: add meta tags to blog

### ISSUE THREAD

**Issue by niklasmtj** [denoland/saaskit#31]
To enable OpenGraph descriptions, pictures etc. we should also add the most important meta tags to the blog landing and post pages. What do you think?

**Comment by iuioiua** [comment]
I like that idea. PRs are most welcome.

**Comment by iuioiua** [comment]
Would you like to take this one, @niklasmtj?

**Comment by niklasmtj** [comment]
Yes please. Sorry had some busy days. 

I was thinking about using the great `metas` plugin from Lume ([docs](https://lume.land/plugins/metas/)) as a reference style to add those meta tags via the frontmatter. What do you think?

Otherwise we could also just use the description which is already in the frontmatter. Since most of them are already set somewhere on the pages we could aggregate into the `meta` tags
Maybe the following metas would be a good start:
- description
- title
- url
- site_name
- locale
- type (using website for now I guess)

**Comment by iuioiua** [comment]
Sweet! No rush 👍🏾

I think we should use the existing frontmatter from the post + `constants.ts` + `props.url.origin` (for URLs). Beyond that, I'm open (mainly thinking about how cover photos are done).
