### ISSUE TITLE
todo: basic endpoint testing

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#315]
Before #20 can be actioned, we must validate that route handlers mostly behave within expectations. This can be done simply by asserting that handlers respond with the expected HTTP status code, a body, basic headers, etc. I want to emphasis that this testing only needs to be basic. Some of the routes we should cover include (but aren't exclusive to):
* `GET /`
* `GET /blog`
* `GET /pricing`
* `GET /signin` and other auth pages
* `GET /account` (redirect to sign-page)

For guidance, see https://fresh.deno.dev/docs/examples/writing-tests

**Comment by mbhrznr** [comment]
i'd tackle this one!
