### ISSUE TITLE
bug: notification red dot went to corner of the screen

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#335]
probably has to do with some relative/absolute twind config

<img width="449" alt="Screenshot 2023-07-03 at 00 10 37" src="https://github.com/denoland/saaskit/assets/8139585/c93f6989-eddd-4eae-a09b-917eed01ad7b">

**Comment by iuioiua** [comment]
I recently made some front-end changes that would've caused this. My bad.

**Comment by iuioiua** [comment]
Completed in #337.
