### ISSUE TITLE
todo: replace `formatDate()` with `zeroizeUTCTime()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#340]
Storing data using `formatDate()` in the key is inconsistent with how dates are represented in keys in the rest of the codebase. It may also be unclear exactly what `formatDate()` does. It can be replaced with:

```ts
export function zeroizeUTCTime(date: Date) {
  date.setUTCHours(0, 0, 0, 0);
  return date;
}
```

This would require:
1. A migration from the old keys that used `formateDate()` to the new keys which use `zeroizeUTCTime()`.
2. A rework of the corresponding tests.

**Comment by mbhrznr** [comment]
what would be the expected output of `zeroizeUTCTime `?
`Date`, timestamp or iso string?

**Comment by iuioiua** [comment]
Actually, on second thought, this change might not be needed. I'll close this issue for now.
