### ISSUE TITLE
todo: link to user GitHub profile page

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#347]
On [each account page](https://hunt.deno.land/user/iuioiua), there should be a link to the user's GitHub profile page as part of the user details. The GitHub icon component in `/components/icon.tsx` can be used.

**Comment by niklasmtj** [comment]
What do you think about putting the icon in front of the number of submissions? So in your case `<GitHub> | 16 submission` or even underneath that? This way we could prepare a place for more links in the future like personal website etc.

**Comment by iuioiua** [comment]
I'm open to ideas.
