### ISSUE TITLE
proposal: personal website link on user profile

### ISSUE THREAD

**Issue by niklasmtj** [denoland/saaskit#360]
What do you think about adding the option to link to one's personal website/blog? After adding the GitHub profile in #356, I would suggest adding this as an additional option.

My suggestion would be to place the icon right next to the GitHub logo like this:
<img width="1334" alt="user profile" src="https://github.com/denoland/saaskit/assets/22395665/b3c1b3dc-295f-46be-b0f4-9216621e4b59">

Editing is then possible via the `/account' page as follows:
<img width="1289" alt="user account settings" src="https://github.com/denoland/saaskit/assets/22395665/09fc853e-2167-4b0a-a1b7-8e98e353d180">

Happy to get feedback!

**Comment by iuioiua** [comment]
I prefer not to do this. The current link to the GitHub user's profile already has their website, social and other URLs.
