### ISSUE TITLE
proposal: disallow duplicate entries

### ISSUE THREAD

**Issue by boywithkeyboard** [denoland/saaskit#377]
I'd suggest to disallow duplicate entries (within a certain timeframe) or rate limit post functionality heavily to make spamming more difficult.

**Comment by iuioiua** [comment]
Yep, I think this would be great to have.

**Comment by boywithkeyboard** [comment]
One post every 6h should be enough for a single user in my opinion.

**Comment by iuioiua** [comment]
I think disallowing duplicate entries is sufficient. Let's see how we go just doing that first 👍🏾
