### ISSUE TITLE
Type Error of SupabaseClient on the Supabase version of Sasskit

### ISSUE THREAD

**Issue by CarcajadaArtificial** [denoland/saaskit#397]
I cloned the SassKit version that runs on Supabase, as suggested by the README.md file. I understand that this version is months old, so I'm not looking for a fix to be implemented in the project since it switched to Deno KV.

The issue happens after cloning the project, setting up the env variables, and starting the Supabase server. But I get a weird type error inside: https://github.com/denoland/saaskit/blob/3b1b14a97eef8859596015b22557d575d3b63c09/routes/_middleware.ts#L27

```
Type 'import("https://esm.sh/v129/@supabase/supabase-js@2.29.0/dist/module/SupabaseClient").default<import("file:///Users/poncho/git/saaskit/utils/supabase_types").Database, "public", { Tables: { comments: { Row: { created_at: string; id: string; item_id: string; text: string; user_id: string; }; Insert: { ...; }; Update:...' is not assignable to type 'import("https://esm.sh/v129/@supabase/supabase-js@2.14.0/dist/module/SupabaseClient").default<import("file:///Users/poncho/git/saaskit/utils/supabase_types").Database, "public", { Tables: { comments: { Row: { created_at: string; id: string; item_id: string; text: string; user_id: string; }; Insert: { ...; }; Update:...'.
  Property 'supabaseUrl' is protected but type 'SupabaseClient<Database, SchemaName, Schema>' is not a class derived from 'SupabaseClient<Database, SchemaName, Schema>'.deno-ts(2322)
```

What I can understand from the error is that there's a discrepancy between `supabaseClient` types from version 2.14.0 vs 2.29.0. I've tried changing the dependency version from 2.14.0 (the original Supabase dependency in SassKit) to 2.29.0 and still doesn't work.

Thank you.

**Comment by iuioiua** [comment]
Could you please clarify which branch or tree you're using? Also, to eliminate any basic assumptions, please share the `deno --version` output.

**Comment by CarcajadaArtificial** [comment]
Certainly, the version I'm using is the one cited in the Project's Readme: "Prefer using Supabase for data storage? [Check out this version of SaaSKit](https://github.com/denoland/saaskit/tree/3b1b14a97eef8859596015b22557d575d3b63c09)." The commit id is `3b1b14a97e`. The output of `deno --version` is:
```
deno 1.35.2 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```

**Comment by iuioiua** [comment]
Hi @CarcajadaArtificial, sorry for the delay in getting back to you. I was never able to reproduce the issue. Are you still experiencing this issue?

**Comment by iuioiua** [comment]
Gentle ping, @CarcajadaArtificial

**Comment by CarcajadaArtificial** [comment]
Sorry, I completely missed this. I was never able to figure it out and coincidently was whitelisted in DenoKV for Deno Deploy so I've been using that ever since. I'm really sorry for my delayed answer, I wish I had information that was a little more useful. I thank you for your interest in this issue tho

**Comment by iuioiua** [comment]
All good! Thanks for getting back to me.
