### ISSUE TITLE
Proposal: add pagination for the users tab

### ISSUE THREAD

**Issue by brunocorrea23** [denoland/saaskit#398]
https://hunt.deno.land/dashboard/users

**Comment by iuioiua** [comment]
I agree. However, I'd like this done differently from how pagination is done in the rest of the codebase, which I now realise is a little hacky.

It should be done how pagination was originally intended to be implemented: https://deno-blog.com/A_Comprehensive_Guide_to_Deno_KV.2023-06-30#pagination-with-list
