### ISSUE TITLE
proposal: remove use of `user.id`

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#400]
I propose we remove all use of `user.id` in favour of `user.login`. This would:
1. Reduce the number of unique identifiers in the `user` object from 2 to 1.
2. Remove the need for KV-flavoured joins.
3. Enable pagination to be implemented in a less hacky way than it currently is.

E.g. if this were done, this would remove the need for [`getManyUsers()` in `/routes/index.tsx`](https://github.com/denoland/saaskit/blob/8476598a8fd5ff3bed41244afe03f518ae342571/routes/index.tsx#L50C30-L50C42).

This would involve refactoring item, vote, user and notification logic. However, the difficult part is migrating existing data cleanly in KV.

Any help with this would be greatly appreciated. Please be sure to let us know if you'd like to help here.

**Comment by iuioiua** [comment]
I'll shortly be submitting a PR addressing the codebase changes. From there, we can look at the migration.

**Comment by roberto-morado** [comment]
### I can help, assign as you deem appropriate
