### ISSUE TITLE
Bug: An error occurred during route handling or page rendering

### ISSUE THREAD

**Issue by ivanlori** [denoland/saaskit#403]
**Describe the bug**
Console error during the first run of `deno task start`.

**To Reproduce**:

1. Follow installation
2. Skip the part about Stripe
3. Run `deno task start`
4. See error in console

**Expected behavior**
To run correctly without errors

**Screenshots**
<img width="1380" alt="image" src="https://github.com/denoland/saaskit/assets/7620920/0a8f8c43-57eb-46bf-bd5a-ff6e3d5303e7">

**Desktop (please complete the following information):**
Typing `deno --version`
- deno 1.35.1 (release, x86_64-apple-darwin)
- v8 11.6.189.7
- typescript 5.1.6

**Additional context**
I've followed the README.md installation skipping the part about Stripe settings since is optional.

**Comment by ivanlori** [comment]
*Update* This error occurs when I navigate to the pricing page; if I return to the dashboard page, stop the execution from the CLI and rerun the process, the error remains.

**Comment by iuioiua** [comment]
Interesting... If the Stripe instructions are skipped, then the `STRIPE_SECRET_KEY` environment variable wouldn't be defined, meaning that `GET /pricing` would return a not found page.

Either way, your screenshot shows that OAuth is failing on the callback route. Can you please try the following:
1. Double-check that [OAuth is configured](https://github.com/denoland/saaskit#auth-oauth) correctly
2. Try navigating to `http://localhost:8000/signin`

Please let me know how you go, as I cannot reproduce the issue.

**Comment by ivanlori** [comment]
1. Yes I have configured the Auth APP on github and filled my .env file as requested by the docs, the only difference I've deleted the example strings from Stripe keys;
<img width="863" alt="image" src="https://github.com/denoland/saaskit/assets/7620920/fbf0dff5-5d8f-4399-995f-28af3e26b2ff">
2. Screen of what I see on the pricing page
<img width="1380" alt="image" src="https://github.com/denoland/saaskit/assets/7620920/e7a990df-1e05-43e0-8359-10842fc3beeb">

**Comment by iuioiua** [comment]
Your Stripe-related environment variable keys exist in your `.env` file. However, these environment variables have empty values. Is this correct?

If so, that'd make sense. It'd be caused by the `cp .example.env .env` step in the README. I've submitted the initial PR in #404 to fix this issue and will let you know once merged.

In the meantime, please remove Stripe-related environment variable keys from your `.env` and let me know if it fixes the issue.

**Comment by ivanlori** [comment]
Yes! Removing totally those keys works. I should have tried the delete, thanks!
