### ISSUE TITLE
proposal: remove vote functionality

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#434]
Deno Hunt aims to emulate Hacker News and Product Hunt roughly. Vote functionality is a vital part of HN and PH. However, having such functionality may be extraneous to Deno Hunt / SaaSKit and not worth the complexity.

There are quite a few moving parts to vote functionality that, if removed, would simplify maintenance of the codebase. I don't think the site's "coolness" would suffer. It'd make implementing other site features far less painless. E.g. REST API and search.

I propose we remove all vote functionality.

**Comment by mbhrznr** [comment]
would there be an alternative to rank items or boost an item's visibility?

just thinking loudly, what about ranking by activity, such as the amount of comments or individual visits?
yet i assume we'd need to have secondary indices for both of them as well?

**Comment by huai-jie** [comment]
Ya, I agree with @mbhrznr 

I don't mind removing it. 

But is there any alternative way to let the 'good items' get more chance to catch users' interest?

**Comment by roberto-morado** [comment]
Although your point is understandable, I'd have to say that the vote functionality allows for interactivity, unless I could somehow "save" the links that I like, I recommend leaving it.

**Comment by iuioiua** [comment]
I hear the sentiments against... I was thinking of instead pursuing comments count as a value indicator.

**Comment by iuioiua** [comment]
Let's keep the voting functionality. We have a few changes in the works that'll make the functionality easier to work with. If we change minds, we'll re-open this issue.
