### ISSUE TITLE
todo: remove `getManyValues()` and `getDatesSince()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#464]
[`getManyValues()`](https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/utils/db.ts#L27-L37) is used in [`getManyMetrics()`](https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/utils/db.ts#L547-L554). It's slightly hacky in that it defines the exact dates to get values. It should instead use [`kv.list()`](https://deno.land/api@v1.36.3?s=Deno.Kv&unstable=&p=prototype.list) with the [`selector`](https://deno.land/api@v1.36.3?s=Deno.KvListSelector&unstable=) parameter being set to have a `start` property of x time ago, using [`formatDate()`](https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/utils/db.ts#L66-L68).

This also means aiming to remove [`getDatesSince()`](https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/utils/db.ts#L46-L57).

**Comment by mbhrznr** [comment]
quick heads-up:
we've chosen to use exact dates to fix #276.
by using `kv.list` we would potentially re-introduce unwanted side-effects, wouldn't we?

however we might want to add some further documentation on that topic.

**Comment by iuioiua** [comment]
Yeah... I played with this today, only to quickly remind myself why we did this in the first place. I'll close this for now and re-open it if I come up with a decent solution. If you do first, please let me know 🙂
