### ISSUE TITLE
todo: remove `assertIsEntry()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#465]
[`assertIsEntry()`](https://github.com/denoland/saaskit/blob/0f61d354a36d4f877c58feb162531d3cf087e5f7/utils/db.ts#L39-L43) looks like it might not be used anywhere. This needs to be confirmed, though.

**Comment by gaurab-khanal** [comment]
Can I work on this issue? Also, can you elaborate more?

**Comment by iuioiua** [comment]
That'd be great! Thanks. You'll need to determine if `assertIsEntry()` is used anywhere in the codebase and remove its use where it's reasonable to do so. It may no longer be used anywhere in the codebase.

**Comment by gaurab-khanal** [comment]
> That'd be great! Thanks. You'll need to determine if `assertIsEntry()` is used anywhere in the codebase and remove its use where it's reasonable to do so. It may no longer be used anywhere in the codebase.

Should I need to remove `assertIsEntry()` from the codebase if it is not used anywhere in codebase?

**Comment by iuioiua** [comment]
> Should I need to remove `assertIsEntry()` from the codebase if it is not used anywhere in codebase?

Yes, the aim is to remove `assertIsEntry()` from the codebase.

**Comment by gaurab-khanal** [comment]
> > Should I need to remove `assertIsEntry()` from the codebase if it is not used anywhere in codebase?
> 
> Yes, the aim is to remove `assertIsEntry()` from the codebase.

Could you review my PR?
