### ISSUE TITLE
todo: remove bullet points from notification rows

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#467]
The bullets to the right of the "New vote!" text in the screenshot below should be removed.

![hunt deno land_notifications](https://github.com/denoland/saaskit/assets/29347852/547cf919-910a-43a8-a7cd-43469ec8540e)

**Comment by ekkaaditya200** [comment]
Hey i want to do it, can you assign me

**Comment by iuioiua** [comment]
Yep! Done 👍🏾 thank you
