### ISSUE TITLE
todo: improve user page header

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#468]
The current user page header looks like this:
<img width="1470" alt="Screenshot 2023-09-01 at 12 05 56 pm" src="https://github.com/denoland/saaskit/assets/29347852/17cf9a9a-9eb2-414b-98ff-5f7bf66bbeec">

I think it'd look nice if:
- Everything was horizontally aligned to the centre - avatar image on the top, username and badge in the middle and GitHub link on the bottom
- Avatar image was bigger

WDYT, @hashrock?

**Comment by hashrock** [comment]
Yeah it would be nice!

**Comment by roberto-morado** [comment]
### Assign me 👋

**Comment by roberto-morado** [comment]
## Which one do you prefer?

@iuioiua 

### Reference

<img width="1304" alt="Screenshot 2023-09-04 at 9 43 18 PM" src="https://github.com/denoland/saaskit/assets/122580309/61857429-e052-486a-bed9-74be208c325c">

### Alternatives

<img width="1293" alt="Screenshot 2023-09-04 at 9 38 31 PM" src="https://github.com/denoland/saaskit/assets/122580309/3ffba77b-7d67-4780-ab38-403e24c97fdf">

<img width="1308" alt="Screenshot 2023-09-04 at 9 45 11 PM" src="https://github.com/denoland/saaskit/assets/122580309/6a22ba46-30b3-428a-a2ac-ae55d9326805">

**Comment by iuioiua** [comment]
Alternative number 2 looks like what we're after. Can you please add a little spacing between the elements?

**Comment by roberto-morado** [comment]
Sure thing.

**Comment by roberto-morado** [comment]
# ?

I prefer the first one.

<img width="252" alt="Screenshot 2023-09-04 at 10 10 30 PM" src="https://github.com/denoland/saaskit/assets/122580309/1f8fd400-b832-4606-92b1-6f25f37296c7">

<img width="246" alt="Screenshot 2023-09-04 at 10 13 44 PM" src="https://github.com/denoland/saaskit/assets/122580309/128b4e13-fb03-4325-9e35-3561c27ecf7b">

<img width="239" alt="Screenshot 2023-09-04 at 10 11 44 PM" src="https://github.com/denoland/saaskit/assets/122580309/560aa548-c5b3-48e6-bee0-c15035d4bedf">

CC @iuioiua

**Comment by iuioiua** [comment]
2nd one feels best to me. Let's explore more in a PR 🙂

**Comment by iuioiua** [comment]
Completed #553
