### ISSUE TITLE
todo: rename and restructure `/tools` folder

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#470]
Suggestion:

- [ ] Rename `/tools` to `/tasks`
- [ ] Have each filename match up to the task name. E.g. `db:reset` task for `/tasks/db_reset.ts`.

**Comment by rj2704** [comment]
Hi, I want to work on this issue. Can you please elaborate on the second point that we need to fix?

**Comment by iuioiua** [comment]
Great! Thank you. The `deno.json` file has a number of tasks. Each task correlates with one of the scripts currently in `/tools`. However, their names do not match their file and function names, as given in my example. The task, file and function names matching makes their purposes clearer.

**Comment by iuioiua** [comment]
Hi, @rj2704. Actually, no need to have a main function since each file is a script. Check out #483. It gives an example of what I'm after by having a `db:migrate` task and the `tasks/db_migrate.ts` script.
