### ISSUE TITLE
Bug report: GitHub oauth redirects to localhost:3000 in demo

### ISSUE THREAD

**Issue by lambtron** [denoland/saaskit#49]
**Describe the bug** 
in the demo, https://saaskit.deno.dev, if you auth via github, you are redirected to localhost:3000

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://saaskit.deno.dev/signup
2. Click on 'Login with GitHub'
3. See error (you'll end up on localhost:3000)

**Expected behavior** 
You should end up on https://saaskit.deno.dev/dashboard.

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1080190/230424045-7ac34711-6c8e-41c7-9fee-dfb0bcdc6c2d.png)

**Desktop (please complete the following information):**
Chrome

**Comment by lambtron** [comment]
I'm wondering if this can be fixed from this supabase config file in the repo:

https://github.com/denoland/saaskit/blob/1363cb03a2756c89dc5f8e13e07e4a9f3e2b6500/supabase/config.toml#L45

or if its something that has to be done in the supabase project orgs in their UI.

**Comment by iuioiua** [comment]
The site URL in the Supabase dashboard was incorrectly set. It's fixed now. Thanks for reporting!
