### ISSUE TITLE
todo(perf): only load `<VoteButton />` island if user is signed in

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#513]
Spec:
- Replace with a component identical in look to `<VoteButton />` when the user is not signed in.
- Upon hover, state "Sign in to vote", possibly using the [`title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title).
- Do not change the mouse state upon hover to avoid misleading the user.

**Comment by ryanponce** [comment]
I took a stab at this issue here. https://github.com/denoland/saaskit/pull/517

**Comment by iuioiua** [comment]
Completed in #517.
