### ISSUE TITLE
Bug report - Deno task start hung

### ISSUE THREAD

**Issue by mallikarjunece** [denoland/saaskit#516]
Bug report

deno task start

Task start deno run --unstable -A --watch=static/,routes/ dev.ts
Watcher Process started.
Download https://raw.githubusercontent.com/lino-levan/deno_std/feat-ulid/dotenv/load.ts

The URL is updated it seems, kindly do the needful.

**Comment by iuioiua** [comment]
Can you access https://raw.githubusercontent.com/lino-levan/deno_std/feat-ulid/dotenv/load.ts in your web browser?

**Comment by iuioiua** [comment]
Hi @mallikarjunece, just following up. I'm unable to reproduce your issue.

**Comment by roberto-morado** [comment]
`deno task start` works fine for me.

**Comment by iuioiua** [comment]
Closing as the issue appears to be network-related. @mallikarjunece, please check your network settings by ensuring you're able to reach https://raw.githubusercontent.com/lino-levan/deno_std/feat-ulid/dotenv/load.ts in your browser.
