### ISSUE TITLE
Docker is an implicit dependency?

### ISSUE THREAD

**Issue by matthew-dean** [denoland/saaskit#57]
**Describe the bug** A clear and concise description of what the bug is.

When running `npx supabase start` from the setup guide, I get: `Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**To Reproduce** Steps to reproduce the behavior:

1. Clone this project
2. Copy `.env.example` to `.env`
3. Run `npx supabase start`

**Expected behavior** A clear and concise description of what you expected to
happen.

The setup guide should state all setup dependencies.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] N/A
- Version [e.g. 22] I don't know how to tell that in Deno?

**Smartphone (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by iuioiua** [comment]
Thanks for bringing this up, @matthew-dean. Yes, agreed - the README should list dependencies, such as docker. I'll include this point in an upcoming change to our documentation.

**Comment by matthew-dean** [comment]
@iuioiua  Thanks so much!

**Comment by iuioiua** [comment]
The documentation has now listed Docker as [a prerequisite](https://github.com/denoland/saaskit#prerequisites). Thanks for letting us know, @matthew-dean!
