### ISSUE TITLE
Feature request: add fresh 1.4 define* helper function

### ISSUE THREAD

**Issue by harshmangalam** [denoland/saaskit#575]
Add fresh 1.4 helpers for route, app and layouts.

**Comment by harshmangalam** [comment]
https://github.com/denoland/saaskit/issues/575

**Comment by harshmangalam** [comment]
https://github.com/denoland/saaskit/pull/574

**Comment by iuioiua** [comment]
Hi @harshmangalam, can you please elaborate on why we need these helpers?

**Comment by harshmangalam** [comment]
https://deno.com/blog/fresh-1.4#quicker-typing-with-define-functions
No need to bother about importing types like RouteContext and shorter for async component.

**Comment by harshmangalam** [comment]
https://github.com/denoland/saaskit/pull/590

**Comment by iuioiua** [comment]
Completed in #590.
