### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by digioak** [denoland/saaskit#588]
**Describe the bug** A clear and concise description of what the bug is.

In `db_seed.ts` task, increasing `TOP_STORIES_COUNT` to larger value (for example, 100), may cause `createUser()` to fail due to duplicate user logins.

**To Reproduce** Steps to reproduce the behavior:

1. Increate `TOP_STORIES_COUNT` to `100`
2. `deno task db:seed`

**Expected behavior** A clear and concise description of what you expected to
happen.

New projects and associated users seed without errors.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: n/a
- Version n/a

**Smartphone (please complete the following information):**

- Device: n/a
- OS: macOS
- Browser: n/a
- Version n/a

**Additional context** Add any other context about the problem here.

**Comment by iuioiua** [comment]
Completed in #589
