### ISSUE TITLE
Bug: Cannot read properties of null (reading 'email') while signup

### ISSUE THREAD

**Issue by austin362667** [denoland/saaskit#59]
Hi, I'm using `SaaSKit`. It's a brilliant example of what I'm looking to do with Deno. Thanks for the great work!!

Getting this error 500 internal error: Cannot read properties of null (reading 'email') while signup.
`Auth` looks good in my configured Supabse but the `customers` table is empty.

The error occurred during this [line](https://github.com/denoland/saaskit/blob/0a99ef7880c87d14f5345e3cacc3754974f36225/utils/supabase.ts#L71) because of empty `user` data.

Maybe it's an issue from Supabase?

**Comment by iuioiua** [comment]
I was able to complete the signup flow without issue. Would you be able to give me more information? Are you using OAuth or email/password?

What do [Supabase auth logs](https://app.supabase.com/project/_/logs/auth-logs) say?

**Comment by austin362667** [comment]
<img width="439" alt="截圖 2023-04-11 上午10 10 21" src="https://user-images.githubusercontent.com/35886692/231037289-77dd2d2f-60a3-4653-b5a2-6826cc6561c4.png">

**Comment by iuioiua** [comment]
I see an HTTP 401 response (unauthorized) on the top row. Could this be related?

Under `Auth` > `Providers` > `Email`, is `Confirm email` disabled as [it should be](https://github.com/denoland/saaskit#setup-authentication)?

**Comment by austin362667** [comment]
No, I don't think so. I've followed these instructions carefully.

What if I enabled the `Confirm email` and verified it, will the error the same?

**Comment by austin362667** [comment]
But I think HTTP 401 response (unauthorized) is an issue not related to this repo.
Closing the issue now. Anyway, thanks a lot for the help!
