### ISSUE TITLE
Discord channel (saaskit) link in README.

### ISSUE THREAD

**Issue by niranjan-kurhade** [denoland/saaskit#636]
**When clicking on the discord channel (saaskit) link in the README:-**

![image](https://github.com/denoland/saaskit/assets/97905637/219086ea-3304-4bef-8575-18fb2e309f15)

**We can't see anything if we haven't joined the Discord server.**

![image](https://github.com/denoland/saaskit/assets/97905637/460850a8-08c1-4de5-bc39-d98ea124dc0f)

**Solution** 
Give the discord server's link and not the channel's link. After someone has joined the server only then can they view the specific channel.

**Comment by niranjan-kurhade** [comment]
If this is a valid issue. Please assign it to me. I would like to fix it and create a PR.

**Comment by iuioiua** [comment]
Thanks for catching, @niranjan-kurhade! I've assigned the issue to you.

**Comment by niranjan-kurhade** [comment]
> Thanks for catching, @niranjan-kurhade! I've assigned the issue to you.

Hey @iuioiua, Thanks! I have created a PR, Please review it.
