### ISSUE TITLE
todo: upgrade to Fresh 1.6

### ISSUE THREAD

**Issue by iuioiua** [denoland/saaskit#644]
SaaSKit needs to be upgraded to [Fresh 1.6, which was just released](https://deno.com/blog/fresh-1.6). We should also switch from using Twind to Tailwind CSS (guide [here](https://fresh.deno.dev/docs/examples/migrating-to-tailwind)). Once this is done, I'll publish a new minor version of SaaSKit.

**Comment by gabobaxx** [comment]
Hi. Why will you change from twind to tailwind? 
I lost track of SassKit a little 🥺

**Comment by iuioiua** [comment]
Hi @gabobaxx, give [this](https://deno.com/blog/fresh-1.6#first-class-tailwind-css-plugin) and [this](https://fresh.deno.dev/docs/examples/migrating-to-tailwind#frequently-asked-questions-faq) a read. I think they should answer your questions 🙂
