### ISSUE TITLE
Trouble getting styles to load on Deno Deploy

### ISSUE THREAD

**Issue by paudrow** [denoland/saaskit#653]
I've forked this repo and tried to run it directly on Deno Deploy. The application loads and seems to have all the parts but no styling. I can view the styling when I run the site locally.

Perhaps I'm missing something obvious, but it would be good to document this.

**To Reproduce**

1. Deploy with Deno Deploy. Set Automatic deployment mode and `main.ts` as the entry point.
2. Go to the deployment website to see that no styles are applied.

**Expected behavior** 
The styling should load.

**Screenshots**

Here is what I see on the website hosted by Deno Deploy:

![Screenshot from 2024-01-05 21-06-45](https://github.com/denoland/saaskit/assets/114802901/4f00756d-7e9d-49b3-8b5b-338eb0773214)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: Brave (also tried Firefox)
- Version 1.61.109

**Additional context**

I don't see anything funny in the build logs or runtime logs.

I'm also able to get styling to work on Deno Deploy using the Fresh template. I'm not sure what's different here.

**Comment by iuioiua** [comment]
Hi Audrow, sorry for the late reply. You've setup the Deno Deploy and GitHub integration mode to Automatic when it should be via a GitHub action. We changed this a while ago but didn't update the documentation. I'll rewrite the documentation shortly and update you once done.

**Comment by paudrow** [comment]
That works great - thanks!

What is it about this project that requires it to be run with Github Actions? Maybe Tailwind?

**Comment by iuioiua** [comment]
Yeah, Tailwind.

**Comment by iuioiua** [comment]
Related: https://fresh.deno.dev/docs/concepts/ahead-of-time-builds
