### ISSUE TITLE
Feature request: Have a more minimal saaskit option

### ISSUE THREAD

**Issue by paudrow** [denoland/saaskit#655]
**Is your feature request related to a problem? Please describe.** 

It takes a bit of work to get the saaskit into a form that I can start building from. It'd be nice to have a more minimal version. 

**Describe the solution you'd like** 

I'd like a repository that has only the following:

* User and auth setup
* Stripe integration

And not the following:

* Blogs
* Graphs
* Items in database

Here is my attempt: https://github.com/paudrow/saaskit-minimal

**Describe alternatives you've considered**

I can delete everything myself, which I've done (link above), but it is something that I have to maintain and possibly fight merge conflicts. It'd be nicer to have an officially maintained version.

**Comment by iuioiua** [comment]
Having two versions of SaaSKit would be difficult to maintain. It'd be better to have a single version that improves its modularity, making it easier to modify. That's what I've tried to do with the addition of plugins.

I'd be happy to hear ideas on how modularity, but I will close this as not planned. Either way, thank you for your suggestion 🙂
