### ISSUE TITLE
Feature request: Tailwind CSS v3.4 `size-*` utilities

### ISSUE THREAD

**Issue by VladimirCreator** [denoland/saaskit#661]
**Is your feature request related to a problem? Please describe.**
It’s not a problem, just a code readability improvement.

**Describe the solution you'd like**
Replace all occurrences of `w-[number]` and `h-[number]` with `size-[number]`.

**Describe alternatives you've considered**
Leave everything as it is.

**Additional context**
Requires Tailwind CSS v3.4.

**Comment by iuioiua** [comment]
Good suggestion. A PR would be welcome 🙂
