### ISSUE TITLE
'new row violates row-level security policy for table "customers"'

### ISSUE THREAD

**Issue by umaar** [denoland/saaskit#78]
Issue when trying to sign up locally, any ideas?

```sh
An error occurred during route handling or page rendering. {
  code: "42501",
  details: null,
  hint: null,
  message: 'new row violates row-level security policy for table "customers"'
}
```

**Comment by iuioiua** [comment]
@umaar, are you able to share a screenshot of the policy configuration for `public.customers`?

**Comment by umaar** [comment]
Sorry been a bit busy, no worries if you can't repro! I believe I saw this while following the getting started guide!
