### ISSUE TITLE
Event type not supported: customer.subscription.updated

### ISSUE THREAD

**Issue by umaar** [denoland/saaskit#79]
If I cancel a subscription from Stripe, I'm seeing 

```
Event type not supported: customer.subscription.updated
```

Does that need to be handled, or is it only `customer.subscription.deleted` that matters? Presumably, when the subscription period has ended, `customer.subscription.deleted` is then sent, even if the sub was already cancelled. If so, I guess this makes sense!

**Comment by iuioiua** [comment]
This may be because your customer portal is configured to cancel at the end of the billing period rather than immediately. Are you able to [confirm](https://dashboard.stripe.com/test/settings/billing/portal)?

Either way, this distinction should be documented.

**Comment by umaar** [comment]
Good shout! 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/381495/231623518-91a64a22-b8f5-4b09-87bb-864f59eb3290.png">

**Comment by iuioiua** [comment]
Thanks, @umaar. I'll be sure to include this in the upcoming documentation rewrite. I'll close this issue for now, though.
