### ISSUE TITLE
Slow signup process

### ISSUE THREAD

**Issue by umaar** [denoland/saaskit#81]
For example, signup taking 16 seconds here:

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/381495/231615481-0cea4c14-bfba-4a3a-9c01-0044d6d70a2a.png">

**Comment by iuioiua** [comment]
I'm not able to reproduce this same slowness on my machine. Are you able to test again?

<img width="1470" alt="Screenshot 2023-04-13 at 5 44 17 pm" src="https://user-images.githubusercontent.com/29347852/231689668-0df61504-2017-4c82-ba5f-0efca51fbfd0.png">

**Comment by iuioiua** [comment]
Are you able to reproduce this issue, @umaar?

**Comment by umaar** [comment]
Haven't tried it again but feel free to close if you can't repro!

**Comment by iuioiua** [comment]
I cannot reproduce this issue. Please feel free to re-open this issue if you encounter the same problem.
