### ISSUE TITLE
Pages are sometimes very slow to load

### ISSUE THREAD

**Issue by umaar** [denoland/saaskit#82]
For example, can't explain why, but if you add more logging, that might be handy!

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/381495/231616165-81b710e4-60a1-40b3-94c8-26419945c2ac.png">

Hard to reproduce, but am curious what's happening under the hood to cause >10 second response times.

**Comment by umaar** [comment]
Not sure if this helps, but straight after a sign up, I see:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/381495/231616414-9b791395-93cb-40b4-940a-0694e101f5a8.png">

And the page tab has a spinner for that time

**Comment by iuioiua** [comment]
Hm... I'm unable to produce this issue. Could there be something else at play?

<img width="1470" alt="Screenshot 2023-04-13 at 11 30 04 am" src="https://user-images.githubusercontent.com/29347852/231622426-410fbe49-d75b-449e-8185-5804b82bbebb.png">

**Comment by umaar** [comment]
Very sporadic! Hard to repro. Feel free to close, or maybe consider adding verbose logging/console.timing so it's clearer where the time is being spent

**Comment by iuioiua** [comment]
Frankly, I think there would have to be more reasons to justify having logging in-built. Imagine having a log printed for every request that's made to a single endpoint. Now multiply that by the amount of endpoints.

Either way, thanks for looking into this and poking around the codebase. The project becomes more correct with every bug that's identified and fixed.
