### ISSUE TITLE
Feature request: CLI installation command

### ISSUE THREAD

**Issue by lambtron** [denoland/saaskit#87]
**Is your feature request related to a problem? Please describe.** 

would be cool to scaffold a SaaSKit project with a command like:

```
deno run -A -r https://deno.com/saaskit my-project
```

see Fresh for example:
https://github.com/denoland/fresh/blob/main/www/routes/index.tsx#L15
https://github.com/denoland/fresh/blob/main/init.ts

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

also this script doesn't need to be on deno.com/saaskit... it could be something else. saaskit.deno.dev? open to ideas.

**Comment by iuioiua** [comment]
I'm closing this as I think it's unnecessary if we have a goofproof "Getting Started" section, which we aim to have in the upcoming README rewrite.
